baseURL = "/"
languageCode = "pl"
title = "Fundacja Więcej Mądrości"
theme = "PaperMod"

[params]
    showReadingTime = true
    showBreadCrumbs = false
    showPostNavLInks = false
    showShareButtons = false
    disableAnchoredHeadings = true

[params.homeInfoParams]
    Title= ""

[params.cover]
    linkFullImages = true

[[menu.main]]
    name = "Wsparcie"
    url = "/posts/wsparcie"
    weight = 3

[[menu.main]]
    name = "Słowa Kluczowe"
    url = "/tags/"
    weight = 4

[[menu.main]]
    name = "Archiwum"
    url = "/archives/"
    weight = 5

[[menu.main]]
    name = "Kontakt"
    url = "/kontakt/"
    weight = 6
